#!/usr/bin/env python3
"""Regenerate external OES32 reference vectors from the upstream OES-Resilience release.

The scores in ``tests/fixtures/oes_resilience_v0_4_0_oes32_reference.json`` are
computed by the *upstream* ``oes_resilience.detectors.OES32Detector`` (not by this
kit), so ``tests/test_upstream_reference.py`` is an external conformance check
rather than a comparison of this implementation with itself.

Usage (requires a checkout of the upstream repository at the pinned commit)::

    git clone https://github.com/sparkainlp-x/oes-resilience.git /tmp/oes-resilience
    git -C /tmp/oes-resilience checkout v0.4.0
    python3 tools/make_upstream_oes32_reference.py --upstream /tmp/oes-resilience

A native OES32 frame is one 32-channel block, so the upstream detector is run with
``Config(channels=32, block_size=32)`` (one block per frame). All inputs are
synthetic.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import subprocess
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
FIXTURE = ROOT / "tests" / "fixtures" / "oes_resilience_v0_4_0_oes32_reference.json"
UPSTREAM_REPOSITORY = "https://github.com/sparkainlp-x/oes-resilience"
UPSTREAM_TAG = "v0.4.0"
UPSTREAM_COMMIT = "15692152f1851bde617efd3a61fc09485dbe8ed7"
DATA_FILES = ("data/demo_calibration.jsonl", "data/demo_holdout.jsonl")


def fixed_vectors() -> list[tuple[str, list[float]]]:
    """Deterministic synthetic 32-channel frames covering simple edge cases."""
    ramp = [i / 10 for i in range(1, 33)]
    vectors: list[tuple[str, list[float]]] = [
        ("all_zero", [0.0] * 32),
        ("constant_positive", [0.25] * 32),
        ("constant_negative", [-0.25] * 32),
        ("ramp_0.1_to_3.2", ramp),
        ("alternating_sign_ramp", [v if i % 2 == 0 else -v for i, v in enumerate(ramp)]),
        ("single_positive_spike", [0.0] * 31 + [1.0]),
        ("single_negative_spike", [-2.5] + [0.0] * 31),
        ("common_offset_0.6", [0.6] * 32),
        ("large_magnitude_mixed", [1e6 if i % 4 == 0 else -1e-6 * i for i in range(32)]),
        ("tiny_values", [1e-12 * (i - 16) for i in range(32)]),
    ]
    rng = np.random.default_rng(20261005)
    for k in range(12):
        scale = (0.05, 0.1, 0.5, 2.0)[k % 4]
        vectors.append((f"seeded_normal_{k:02d}_sd{scale}", [float(v) for v in rng.normal(0.0, scale, 32)]))
    return vectors


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--upstream", required=True, help="path to an oes-resilience checkout at the pinned commit")
    args = parser.parse_args()
    upstream = Path(args.upstream).resolve()
    head = subprocess.run(["git", "-C", str(upstream), "rev-parse", "HEAD"], check=True,
                          capture_output=True, text=True).stdout.strip()
    if head != UPSTREAM_COMMIT:
        raise SystemExit(f"upstream checkout is at {head}, expected {UPSTREAM_COMMIT} ({UPSTREAM_TAG})")
    sys.path.insert(0, str(upstream))
    import oes_resilience  # noqa: PLC0415
    from oes_resilience import Config  # noqa: PLC0415
    from oes_resilience.detectors import OES32Detector  # noqa: PLC0415

    sys.path.insert(0, str(ROOT))
    from oes_telemetry_bench.bench import load_replay  # noqa: PLC0415

    detector = OES32Detector(Config(channels=32, block_size=32))

    def upstream_scores(frames: np.ndarray) -> list[float]:
        scores = detector.score(frames)
        assert scores.shape == (frames.shape[0], 1)
        return [float(s) for s in scores[:, 0]]

    vectors = fixed_vectors()
    vector_scores = upstream_scores(np.asarray([v for _, v in vectors], dtype=np.float64))
    data_files = []
    for rel in DATA_FILES:
        path = ROOT / rel
        replay = load_replay(path)
        frames = np.asarray([frame.channels for frame in replay.frames], dtype=np.float64)
        data_files.append({
            "path": rel,
            "sha256": hashlib.sha256(path.read_bytes()).hexdigest(),
            "frame_count": int(frames.shape[0]),
            "upstream_scores": upstream_scores(frames),
        })

    fixture = {
        "description": (
            "External reference scores computed by the upstream OES-Resilience OES32Detector "
            "on fixed SYNTHETIC 32-channel frames and on the bundled SYNTHETIC demo replays. "
            "Generated by tools/make_upstream_oes32_reference.py; not computed by oes-telemetry-bench."
        ),
        "upstream": {
            "repository": UPSTREAM_REPOSITORY,
            "tag": UPSTREAM_TAG,
            "commit": UPSTREAM_COMMIT,
            "package_version": oes_resilience.__version__,
            "detector": "oes_resilience.detectors.OES32Detector",
            "config": "Config(channels=32, block_size=32)  # one 32-channel block per native frame",
            "weights": dict(detector.params()["weights"]),
        },
        "generator_environment": {"numpy": np.__version__, "python": sys.version.split()[0]},
        "fixed_vectors": [
            {"name": name, "channels": values, "upstream_score": score}
            for (name, values), score in zip(vectors, vector_scores)
        ],
        "data_files": data_files,
    }
    FIXTURE.parent.mkdir(parents=True, exist_ok=True)
    FIXTURE.write_text(json.dumps(fixture, indent=1) + "\n", encoding="utf-8")
    print(f"Wrote {FIXTURE.relative_to(ROOT)}: {len(vectors)} fixed vectors, "
          f"{sum(d['frame_count'] for d in data_files)} demo frames")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
